# Generated by Django 3.2.25 on 2025-05-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
