# Generated by Django 3.2.25 on 2025-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_destination', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('short_info', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
