# Generated by Django 3.2.25 on 2025-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='short_info',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='destinations/default.jpg', upload_to='destinations/'),
            preserve_default=False,
        ),
    ]
