# Generated by Django 3.2.25 on 2025-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20250513_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
    ]
