# Generated by Django 4.2 on 2025-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
