# Generated by Django 4.2 on 2025-05-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
