# Generated by Django 4.2 on 2025-05-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_rename_signup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Signup',
        ),
    ]
