# Generated by Django 4.2 on 2025-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_rename_user_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_info',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
