# Generated by Django 4.2 on 2025-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_destination_latitude_destination_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='short_info',
            field=models.TextField(default='No description available'),
        ),
    ]
