# Generated by Django 4.2 on 2025-05-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_destination_short_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
    ]
