# Generated by Django 4.2 on 2025-06-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_remove_destination_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='short_info',
            new_name='Description',
        ),
    ]
