# Generated by Django 4.2 on 2025-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_rename_short_info_destination_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport', models.CharField(max_length=50)),
                ('accommodation', models.CharField(max_length=50)),
                ('star_rating', models.IntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('itinerary', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
