# Generated by Django 4.2 on 2025-06-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
